apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app-deployment
  name: app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-deployment
    spec:
      containers:
      - image: raphkaira/train-awwwards
        name: train-awwwards
        ports:
        - containerPort: 80
        resources: {}
status: {}
